### ISSUE TITLE
No support for response examples or schema?

### ISSUE THREAD

**Issue by thom-nic** [zanona/swagger-docs#1]
**Update** actually it looks like the `responses...schema` isn't parsed /handled at all..  Even if I define inline like:
```
responses:
  200:
    schema:
      type: object
      properties:
        foo:
          type: string
        bar:
          type: string
```
I see no "example response" information in the doc.  Am I missing something obvious?  I am referencing the swagger 2.0 spec here: https://swagger.io/docs/specification/2-0/describing-responses/ (see the "Response Body" section half way down the page.) 

**Update 2** I also tried adding an example as defined [here](https://swagger.io/docs/specification/2-0/adding-examples/), but don't see any example generated in my doc.  Guessing I'm SOL on response format documentation?

**Original request**

I've got a route that looks like this:
```yaml
paths:
  /users/me:
    get:
      summary: retrieve the current logged-in user
      tags: [users]
      responses:
        401:
          description: not logged in
        200:
          description: OK
          schema:
            $ref: "#/definitions/User"
```
and a model definition in the same file:
```yaml
defintions:
  User:
    type: object
    properties:
      id:
        type: integer
      username:
        type: string
      email:
        description: admin contact address. This may be used for password resets
        type: string
      password:
        type: string
```

generated doc looks like this definitions also do not show up in the sidebar.  Am I doing something wrong?  Thanks.
![screen shot 2018-04-20 at 3 51 54 pm](https://user-images.githubusercontent.com/95562/39070825-d9f78338-44b2-11e8-8791-0debbdb5c1f7.png)
